version: "2.3"

services:
    ros-master:
        build: ./master
        container_name: ros_master
        restart: unless-stopped
        command: stdbuf -o L roslaunch start.launch
        ports:
           - "9090:9090"
           - "11311:11311"
      
    ros-novnc:
        image: wn1980/w-ros:rpi
        depends_on:
            - ros-master
        container_name: ros_novnc
        hostname: w-ros
#        runtime: "nvidia"
        restart: unless-stopped
        privileged: true
        command: startup.sh
        devices:
            - "/dev:/dev"
        volumes:
            - "~/rosuser_home:/home/rosuser/share_folder:rw"
            - "/run/systemd:/run/systemd"
            - "/etc/localtime:/etc/localtime:ro"
            - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
        environment:
            - "VNC_PASSWORD=vnc123"
            - "VNC_RESOLUTION=1920x1080"
            - "ROS_MASTER_URI=http://ros-master:11311"
            - "ROS_IP=172.18.0.3"
#            - "ROS_HOSTNAME=w-ros"
        ports:
            - "5901:5901"
            - "6901:6901"
