version: "2.3"

#networks:
#  ros_network:
#    driver: bridge
    
services:

    ros-master:
        build: ./master
        image: wn1980/w-ros-master:rpi
        container_name: ros_master
        restart: unless-stopped
        command: stdbuf -o L roslaunch start.launch
        volumes:
           - "/etc/localtime:/etc/localtime:ro"
        ports:
           - "9090:9090"
           - "11311:11311"
#        networks:
#           - ros_network

    ros-joystick:
        build: ./joystick
        image: wn1980/w-ros-joystick:rpi
        depends_on:
            - ros-master
        container_name: ros_joystick
        restart: unless-stopped
        privileged: true
        command: stdbuf -o L roslaunch --wait start.launch
#        command: stdbuf -o L roslaunch --wait turtlebot_lidar_teleop joystick.launch
#        command: stdbuf -o L roslaunch --wait teleop_twist_joy teleop.launch
        devices:
            - "/dev/input:/dev/input"
        volumes:
            - "/dev/input:/dev/input"
            - "/etc/localtime:/etc/localtime:ro"
        environment:
            - "ROS_MASTER_URI=http://ros-master:11311"
            
    ros-novnc:
#        build: ./robot
        image: wn1980/w-ros:rpi
        depends_on:
            - ros-master
        container_name: ros_novnc
        hostname: ros-novnc
        restart: unless-stopped
        privileged: true
        command: startup.sh
        devices:
            - "/dev:/dev"
        volumes:
            - "/dev:/dev"
            - "./Documents:/home/rosuser/Documents:rw"
            - "/run/systemd:/run/systemd"
            - "/etc/localtime:/etc/localtime:ro"
            - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
        environment:
            - "VNC_PASSWORD=vnc123"
            - "VNC_RESOLUTION=1920x1080"
            - "ROS_MASTER_URI=http://ros-master:11311"
            - "TURTLEBOT_MAP_FILE=/home/rosuser/Documents/map.yaml"
#            - "ROS_HOSTNAME=ros-novnc"
#            - "ROS_IP=172.18.0.3"
        ports:
            - "5901:5901"
            - "6901:6901"
#        networks:
#            - ros_network
#        runtime: "nvidia"
